### ISSUE TITLE
CQL checker errors on valid CQL filter strings

### ISSUE THREAD

**Issue by wwerst** [DigitalGlobe/CloudServices#30]
The cql_checker function raises exceptions when the CQL filter string is valid: https://github.com/DigitalGlobe/CloudServices/blob/c4df16611017e2682e3403f4e011399b29e2c2cb/ogc-sdk/src/Maxar_OGC/process.py#L256

For example, the following is a valid CQL filter string, but the cql_checker function does not handle the 'BETWEEN' operator. It also has several other issues, such as not having all sources in `source_list`.

`filter = '((acquisitionDate BETWEEN '2023-03-01' AND '2023-03-02'))'`

**Comment by maxar-gcs** [comment]
We've removed the cql_checker function entirely for the moment. v1.3.1 no longer includes this.
